### ISSUE TITLE
change the color 

### ISSUE THREAD

**Issue by kritartha212** [KritiDiyaliSunar/Hotelbooking#11]
change the color in the below page it is so hard to read while hover the button
<img width="316" alt="Screenshot 2021-04-16 132125" src="https://user-images.githubusercontent.com/81207694/115005259-68458880-9ec7-11eb-803c-42377cfbe74d.png">

**Comment by KritiDiyaliSunar** [comment]
Okay, I have changed the color, and uploaded the corrected file. :)
