### ISSUE TITLE
Front end part

### ISSUE THREAD

**Issue by ghost** [KritiDiyaliSunar/Hotelbooking#12]
On the home page under our services remove the button click to know more.
![issue1](https://user-images.githubusercontent.com/81345125/118089348-f25e0f80-b3e7-11eb-8bf8-ac62f381ba92.png)

**Comment by usersanjiv** [comment]
while opening the user register and login page, the footer was different from the home page.

![bug1](https://user-images.githubusercontent.com/81345125/118085745-9a70da00-b3e2-11eb-8c5c-eeae8655dfea.png)

**Comment by KritiDiyaliSunar** [comment]
Okay sure,
I have made the necessary changes to remove the "click to know more" button. I have uploaded the updated files to the main branch as "Updated Codes (Frontend)".
