### ISSUE TITLE
Booking details not stored in database rakha

### ISSUE THREAD

**Issue by ghost** [KritiDiyaliSunar/Hotelbooking#13]
Booking information was not stored in a database.

![bug3](https://user-images.githubusercontent.com/81345125/118084911-34d01e00-b3e1-11eb-8a9e-4910963d5b51.png)
![bug4](https://user-images.githubusercontent.com/81345125/118084919-37327800-b3e1-11eb-9b55-f0ff26d36540.png)

**Comment by usersanjiv** [comment]
The same room was booked by two different users.

![bug5](https://user-images.githubusercontent.com/81345125/118085123-8ed0e380-b3e1-11eb-861a-a41c9928520f.png)
![bug6](https://user-images.githubusercontent.com/81345125/118085129-91cbd400-b3e1-11eb-80e1-c66d7697feb9.png)

**Comment by usersanjiv** [comment]
while the user was logged in, the page was not redirected to the home page.

![bug2](https://user-images.githubusercontent.com/81345125/118085254-d48dac00-b3e1-11eb-8237-9d8a6ea7a23b.png)

**Comment by ghost** [comment]
request.user refers to the specific instances of the user model which will allow us to access all the files. So, after adding request.user in bookingform function, every information related with rooms are saved in our system's database.

![Screenshot (956)](https://user-images.githubusercontent.com/81345329/118154651-0846f100-b437-11eb-8cf8-e32352d446b9.png)

In admin panel, rooms details are stored in this format.
![Screenshot (975)](https://user-images.githubusercontent.com/81345329/118154927-5e1b9900-b437-11eb-8eec-3ea69435f391.png)

Whereas in web page, room details are stored in this format.
![Screenshot (976)](https://user-images.githubusercontent.com/81345329/118154933-5fe55c80-b437-11eb-98e9-81437f4e3e09.png)
