### ISSUE TITLE
Admin part

### ISSUE THREAD

**Issue by ghost** [KritiDiyaliSunar/Hotelbooking#14]
admin page was not showing the login page.

![bug7](https://user-images.githubusercontent.com/81345125/118085585-5bdb1f80-b3e2-11eb-81b4-e64628bc5064.png)

**Comment by Apexpredator9** [comment]
![image](https://user-images.githubusercontent.com/81209633/118392053-33a82680-b657-11eb-8ba8-39d658493cc3.png)
