### ISSUE TITLE
login was not redirected

### ISSUE THREAD

**Issue by ghost** [KritiDiyaliSunar/Hotelbooking#16]
after the successful login of the user, the login page was not redirected to home.

![bug2](https://user-images.githubusercontent.com/81345125/118089159-c9d61580-b3e7-11eb-8a02-aef7d1b4e502.png)

**Comment by shru9336** [comment]
Providing response to the function fixes this problem.


Here, I added HttpResponseRedirect to userlogin function, which will redirect the page to the main page.

![Screenshot (936)](https://user-images.githubusercontent.com/81345329/118148948-c9ae3800-b430-11eb-9c50-b0c4cfa9274f.png)

![Screenshot (937)](https://user-images.githubusercontent.com/81345329/118152026-f9ab0a80-b433-11eb-889f-4ca9f1e9eed8.png)

![Screenshot (938)](https://user-images.githubusercontent.com/81345329/118152033-fc0d6480-b433-11eb-9684-4f382043303e.png)

**Comment by ghost** [comment]
Providing response to the function fixes this problem.


Here, I added HttpResponseRedirect to userlogin function, which will redirect the page to the main page.

![Screenshot (936)](https://user-images.githubusercontent.com/81345329/118152334-48f13b00-b434-11eb-8b63-c0277255a836.png)

![Screenshot (937)](https://user-images.githubusercontent.com/81345329/118152318-45f64a80-b434-11eb-872f-a9cfedaf1141.png)

![Screenshot (938)](https://user-images.githubusercontent.com/81345329/118152328-47c00e00-b434-11eb-8506-8398806a649b.png)
