### ISSUE TITLE
footer part

### ISSUE THREAD

**Issue by ghost** [KritiDiyaliSunar/Hotelbooking#17]
while opening the user register and login page, the footer was different from the home page. make it similar to in the home page 

![bug1](https://user-images.githubusercontent.com/81345125/118115546-d0c15000-b408-11eb-9e64-b4b91f853431.png)

**Comment by KritiDiyaliSunar** [comment]
Okay sure,
I have made the necessary changes to make the user page's footer similar to the home page's footer. I have uploaded the updated files to the main branch as "Updated Codes (Frontend)".
