### ISSUE TITLE
Update in CSS. 

### ISSUE THREAD

**Issue by ghost** [KritiDiyaliSunar/Hotelbooking#8]
In the login/register form area, there is no proper CSS applied.
![Screenshot (468)](https://user-images.githubusercontent.com/81345329/114973871-03773780-9ea1-11eb-8dc6-54eca0458c85.png)

![Screenshot (469)](https://user-images.githubusercontent.com/81345329/114973858-007c4700-9ea1-11eb-8259-95ccd2ad84e1.png)

**Comment by KritiDiyaliSunar** [comment]
Okay, I have made the changes in CSS and uploaded the files.
